#!/bin/bash
cap=$(xset -q | grep Caps | awk '{print $4}')




if grep -q '^1$' /sys/class/leds/*::capslock/brightness 2>/dev/null; then
	echo "<span color='#00ff00'> CAPS ON</span>"
else
	# echo -n "<span color='#222222'>CAPS</span>"
	echo ""
fi


# ⇩
# ⇧

