#!/usr/bin/env python3

import i3ipc
import sys

i3 = i3ipc.Connection()

def printwin(i3, e):

    if (len(sys.argv)>1):
        a = sys.argv[1]
    else:
        a="xi"

    print("<span color='red'>%s</span>" % (a))
    sys.stdout.flush()


printwin(i3, None)

i3.on('window::new', printwin)
i3.on('window::close', printwin)
i3.on('workspace::focus', printwin)

i3.main()






