#!/bin/bash

INPUT="$1"

MAX=$(brightnessctl max)
MIN=$(echo "$MAX * 0.05" | bc)

# Set brightness
brightnessctl --min-value=$MIN set "$INPUT%" > /dev/null

# Get current brightness
CUR=$(brightnessctl get)

# Calculate percentage (rounded)
PERCENT=$(echo "scale=2; $CUR * 100 / $MAX" | bc)
PERCENT=$(printf "%.0f" "$PERCENT")


# Notify
notify-send \
    -a brightness \
	-h string:x-canonical-private-synchronous:brightness \
	-r 999 \
	-t 200 \
    -h int:value:"$PERCENT" \
    "Brightness" "$PERCENT%"
