#!/bin/sh

case "$1" in
    up)   pamixer -i 5 ;;
    down) pamixer -d 5 ;;
    mute) pamixer -t ;;
    *) exit 1 ;;
esac

# Refresh i3blocks
pkill -RTMIN+1 i3blocks

vol=$(pamixer --get-volume)
mute=$(pamixer --get-mute)



if [ "$mute" = "true" ]; then
	val=0
	text="muted"
else
	val="$vol"
	text="Volume" "$vol%"
fi


notify-send \
	-a volume \
	-h string:x-canonical-private-synchronous:volume \
	-r 999 \
	-t 200 \
	-h int:value:"$val" \
	"$text"




# if [ "$mute" = "true" ]; then
    # notify-send \
        # -a volume \
        # -h string:x-canonical-private-synchronous:volume \
		# -r 999 \
		# -t 200 \
        # -h int:value:0 \
        # "Volume" "Muted"
# else
    # notify-send \
        # -a volume \
        # -h string:x-canonical-private-synchronous:volume \
		# -r 999 \
		# -t 200 \
        # -h int:value:"$vol" \
        # "Volume" "$vol%"
# fi



